spring:
    mongodb:
      uri: { Connection string }
    data:
     auto-index-creation: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: {mail}
      password: { app-password }
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

logging:
  level:
    org.springframework.mail: DEBUG
    org.eclipse.angus.mail: DEBUG

server:
  port: 8081