spring:
  mongodb:
    uri: ${MONGODB_URI}

  data:
    auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.mail: DEBUG
    org.eclipse.angus.mail: DEBUG

server:
  port: 8081